apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "push-notification-service.fullname" . }}
  labels:
    {{- include "push-notification-service.labels" . | nindent 4 }}

data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}