{{ $cacertsFileName := printf "%s%s" "secrets/" .Values.cacertsFile }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "push-notification-service.fullname" . }}
  labels:
    {{- include "push-notification-service.labels" . | nindent 4 }}

type: Opaque

data:
  {{- range $path, $d := .Files.Glob "secrets/*" }}
  {{- if ne $path $cacertsFileName}}
  {{ $path | replace "secrets/" "" }}: >-
  {{- $d | toString | b64enc | nindent 4 }}
  {{ end }}
  {{- end }}