{{ $cacertsFileName := printf "%s%s" "secrets/" .Values.cacertsFile }}
{{ $cacertsFile := .Files.Get $cacertsFileName }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "push-notification-service.fullname" . }}-cacerts
  labels:
    {{- include "push-notification-service.labels" . | nindent 4 }}

type: Opaque

data:
  {{- if $cacertsFile }}
  {{ .Values.cacertsFile }}: >-
    {{ $cacertsFile | b64enc }}

{{- end }}